### ISSUE TITLE
OSError: [Errno 5] Input/output error with Metro M7

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_MLX90640#36]
Re this thread:
https://forums.adafruit.com/viewtopic.php?t=204722

Poster is using Airlift version.

Seeing same thing on non-Airlift (PID 5600) version:
```python
Adafruit CircuitPython 8.2.6 on 2023-09-12; Metro MIMXRT1011 with IMXRT1011DAE5A
>>> import board
>>> import adafruit_mlx90640
>>> i2c = board.STEMMA_I2C()
>>> mlx = adafruit_mlx90640.MLX90640(i2c)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_mlx90640.py", line 95, in __init__
  File "adafruit_mlx90640.py", line 839, in _I2CReadWords
OSError: [Errno 5] Input/output error
>>> 
```

**Comment by ubuntuslave** [comment]
I also encountered the same issue on a Adafruit Metro M7 with microSD

**Comment by snaens** [comment]
I'm having the same issue with a USB->I2C adapter on linux and Adafruit_Python_Extended_Bus
